echo "start the move the files"
mkdir Histogram/1D;
mkdir Histogram/1D/topana;
mkdir Histogram/1D/topana/sideband;
mkdir Histogram/1D/nminusone;
mkdir Histogram/1D/Q;
mkdir Histogram/1D/Qsideband;
mkdir Histogram/1D/S;
mkdir Histogram/1D/Ssideband;
mkdir Histogram/1D/T;
mkdir Histogram/1D/W;
mkdir Histogram/1D/Z;
mkdir Histogram/1D/G;
mkdir Histogram/2D/Q;
mkdir Histogram/2D/Qsideband;
mkdir Histogram/2D/S;
mkdir Histogram/2D/Ssideband;
mkdir Histogram/2D/T;
mkdir Histogram/2D/W;
mkdir Histogram/2D/Z;
mkdir Histogram/2D/G;
mv Histogram/*no* Histogram/1D/nminusone/;
mv Histogram/*topana*s* Histogram/1D/topana/sideband; 
mv Histogram/*topana*q* Histogram/1D/topana/sideband; 
mv Histogram/*topana* Histogram/1D/topana/; 
mv Histogram/*_Q* Histogram/1D/Q/; 
mv Histogram/*_q* Histogram/1D/Qsideband/;
mv Histogram/*_T* Histogram/1D/T/; 
mv Histogram/*_W* Histogram/1D/W/; 
mv Histogram/*_s* Histogram/1D/Ssideband/;
mv Histogram/*_S* Histogram/1D/S/; 
mv Histogram/*_Z* Histogram/1D/Z/; 
mv Histogram/*_G* Histogram/1D/G/; 
mv Histogram/2D/*_Q_* Histogram/2D/Q/; 
mv Histogram/2D/*_q_* Histogram/2D/Qsideband/;
mv Histogram/2D/*_T_* Histogram/2D/T/; 
mv Histogram/2D/*_W_* Histogram/2D/W/; 
mv Histogram/2D/*_s_* Histogram/2D/Ssideband/;
mv Histogram/2D/*_S_* Histogram/2D/S/; 
mv Histogram/2D/*_Z_* Histogram/2D/Z/; 
mv Histogram/2D/*_G_* Histogram/2D/G/; 
